### ISSUE TITLE
Deprecated usage of node-waf

### ISSUE THREAD

**Issue by yangchenyun** [c4milo/fusejs#13]
`npm install fusejs` failed; because of [deprecated node-waf](https://github.com/joyent/node/issues/1716)

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/steveyang/.nvm/versions/io.js/v1.6.1/bin/iojs',
1 verbose cli   '/Users/steveyang/.nvm/versions/io.js/v1.6.1/bin/npm',
1 verbose cli   'install',
1 verbose cli   'fusejs' ]
2 info using npm@2.7.1
3 info using node@v1.6.1
4 silly cache add args [ 'fusejs', null ]
5 verbose cache add spec fusejs
6 silly cache add parsed spec { raw: 'fusejs',
6 silly cache add   scope: null,
6 silly cache add   name: 'fusejs',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed fusejs@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'fusejs', range: '*', hasData: false }
11 silly mapToRegistry name fusejs
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/fusejs
15 verbose addNameRange registry:https://registry.npmjs.org/fusejs not in flight; fetching
16 verbose request uri https://registry.npmjs.org/fusejs
17 verbose request no auth needed
18 info attempt registry request try #1 at 19:52:04
19 verbose request id cb6b2cd0e86903a3
20 verbose etag "AF6QL74HZBA57QQUJ6PBZUPAE"
21 http request GET https://registry.npmjs.org/fusejs
22 http 304 https://registry.npmjs.org/fusejs
23 silly get cb [ 304,
23 silly get   { date: 'Mon, 23 Mar 2015 02:52:05 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Mon, 23 Mar 2015 02:52:05 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"AF6QL74HZBA57QQUJ6PBZUPAE"',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-ord1734-ORD',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1427079125.227905,VS0,VE38',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/fusejs from cache
25 verbose get saving fusejs to /Users/steveyang/.npm/registry.npmjs.org/fusejs/.cache.json
26 silly addNameRange number 2 { name: 'fusejs', range: '*', hasData: true }
27 silly addNameRange versions [ 'fusejs', [ '0.0.1-dev', '0.0.1' ] ]
28 verbose addNamed fusejs@0.0.1
29 silly addNamed semver.valid 0.0.1
30 silly addNamed semver.validRange 0.0.1
31 silly cache afterAdd fusejs@0.0.1
32 verbose afterAdd /Users/steveyang/.npm/fusejs/0.0.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/steveyang/.npm/fusejs/0.0.1/package/package.json written
34 silly install resolved [ { name: 'fusejs',
34 silly install resolved     version: '0.0.1',
34 silly install resolved     author: { name: 'Camilo Aguilar - http://github.com/c4milo' },
34 silly install resolved     email: 'camilo.aguilar@gmail.com',
34 silly install resolved     description: 'Low level Fuse bindings for NodeJS.',
34 silly install resolved     repositories: [ [Object] ],
34 silly install resolved     devDependencies: { mocha: '0.14.1', should: '0.6.0' },
34 silly install resolved     scripts: { install: 'make' },
34 silly install resolved     main: './fuse',
34 silly install resolved     _id: 'fusejs@0.0.1',
34 silly install resolved     dist:
34 silly install resolved      { shasum: '1d300bdc015197b4e69988d96578a7c4de6ce1c5',
34 silly install resolved        tarball: 'http://registry.npmjs.org/fusejs/-/fusejs-0.0.1.tgz' },
34 silly install resolved     _npmVersion: '1.1.63',
34 silly install resolved     _npmUser: { name: 'c4milo', email: 'camilo.aguilar@gmail.com' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     directories: {},
34 silly install resolved     _shasum: '1d300bdc015197b4e69988d96578a7c4de6ce1c5',
34 silly install resolved     _resolved: 'https://registry.npmjs.org/fusejs/-/fusejs-0.0.1.tgz',
34 silly install resolved     _from: 'fusejs@*',
34 silly install resolved     repository: { type: 'git', url: 'http://github.com/c4milo/fusejs.git' },
34 silly install resolved     bugs: { url: 'https://github.com/c4milo/fusejs/issues' },
34 silly install resolved     readme: 'ERROR: No README data found!',
34 silly install resolved     homepage: 'https://github.com/c4milo/fusejs' } ]
35 info install fusejs@0.0.1 into /private/tmp/fe
36 info installOne fusejs@0.0.1
37 verbose installOne of fusejs to /private/tmp/fe not in flight; installing
38 verbose lock using /Users/steveyang/.npm/_locks/fusejs-33444705d2998d8f.lock for /private/tmp/fe/node_modules/fusejs
39 silly install write writing fusejs 0.0.1 to /private/tmp/fe/node_modules/fusejs
40 silly cache addNamed cb fusejs@0.0.1
41 verbose unbuild node_modules/fusejs
42 verbose gentlyRm vacuuming /private/tmp/fe/node_modules/fusejs
43 verbose tar unpack /Users/steveyang/.npm/fusejs/0.0.1/package.tgz
44 verbose tar unpacking to /private/tmp/fe/node_modules/fusejs
45 verbose gentlyRm vacuuming /private/tmp/fe/node_modules/fusejs
46 silly gunzTarPerm modes [ '755', '644' ]
47 silly gunzTarPerm extractEntry package.json
48 silly gunzTarPerm extractEntry .npmignore
49 silly gunzTarPerm extractEntry README.md
50 silly gunzTarPerm extractEntry fuse.js
51 silly gunzTarPerm extractEntry examples/loopback.js
52 silly gunzTarPerm extractEntry examples/loopback_main.js
53 silly gunzTarPerm extractEntry Makefile
54 silly gunzTarPerm extractEntry spec/fuse.spec.js
55 silly gunzTarPerm extractEntry src/filesystem.h
56 silly gunzTarPerm extractEntry src/bindings.cc
57 silly gunzTarPerm extractEntry src/file_info.cc
58 silly gunzTarPerm extractEntry src/file_info.h
59 silly gunzTarPerm extractEntry src/filesystem.cc
60 silly gunzTarPerm extractEntry src/bindings.h
61 silly gunzTarPerm extractEntry src/node_fuse.cc
62 silly gunzTarPerm extractEntry src/node_fuse.h
63 silly gunzTarPerm extractEntry src/reply.cc
64 silly gunzTarPerm extractEntry src/reply.h
65 silly gunzTarPerm extractEntry src/wscript
66 silly gunzTarPerm extractEntry wscript
67 info preinstall fusejs@0.0.1
68 silly install resolved []
69 verbose about to build /private/tmp/fe/node_modules/fusejs
70 info build /private/tmp/fe/node_modules/fusejs
71 verbose linkStuff [ false, false, false, '/private/tmp/fe/node_modules' ]
72 info linkStuff fusejs@0.0.1
73 verbose linkBins fusejs@0.0.1
74 verbose linkMans fusejs@0.0.1
75 verbose rebuildBundles fusejs@0.0.1
76 info install fusejs@0.0.1
77 verbose unsafe-perm in lifecycle true
78 info fusejs@0.0.1 Failed to exec install script
79 verbose unlock done using /Users/steveyang/.npm/_locks/fusejs-33444705d2998d8f.lock for /private/tmp/fe/node_modules/fusejs
80 verbose stack Error: fusejs@0.0.1 install: `make`
80 verbose stack Exit status 2
80 verbose stack     at EventEmitter.<anonymous> (/Users/steveyang/.nvm/versions/io.js/v1.6.1/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
80 verbose stack     at emitTwo (events.js:87:13)
80 verbose stack     at EventEmitter.emit (events.js:169:7)
80 verbose stack     at ChildProcess.<anonymous> (/Users/steveyang/.nvm/versions/io.js/v1.6.1/lib/node_modules/npm/lib/utils/spawn.js:14:12)
80 verbose stack     at emitTwo (events.js:87:13)
80 verbose stack     at ChildProcess.emit (events.js:169:7)
80 verbose stack     at maybeClose (child_process.js:984:16)
80 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
81 verbose pkgid fusejs@0.0.1
82 verbose cwd /private/tmp/fe
83 error Darwin 13.4.0
84 error argv "/Users/steveyang/.nvm/versions/io.js/v1.6.1/bin/iojs" "/Users/steveyang/.nvm/versions/io.js/v1.6.1/bin/npm" "install" "fusejs"
85 error node v1.6.1
86 error npm  v2.7.1
87 error code ELIFECYCLE
88 error fusejs@0.0.1 install: `make`
88 error Exit status 2
89 error Failed at the fusejs@0.0.1 install script 'make'.
89 error This is most likely a problem with the fusejs package,
89 error not with npm itself.
89 error Tell the author that this fails on your system:
89 error     make
89 error You can get their info via:
89 error     npm owner ls fusejs
89 error There is likely additional logging output above.
90 verbose exit [ 1, true ]
91 verbose unbuild node_modules/fusejs
92 info preuninstall fusejs@0.0.1
93 info uninstall fusejs@0.0.1
94 verbose unbuild rmStuff fusejs@0.0.1 from /private/tmp/fe/node_modules
95 info postuninstall fusejs@0.0.1
96 verbose gentlyRm vacuuming /private/tmp/fe/node_modules/fusejs
97 silly gentlyRm purging /private/tmp/fe/node_modules/fusejs
98 silly gentlyRm quitting because other entries in /private/tmp/fe/node_modules
```

**Comment by c4milo** [comment]
Indeed, this is still open https://github.com/c4milo/fusejs/issues/5. If you are looking to use FUSE high level API, you can take a look at https://github.com/bcle/fuse4js instead.

**Comment by yangchenyun** [comment]
Got it. Thx.
